In [2]:
import numpy as np
import pandas as pd

In [3]:
df = pd.read_csv("C:/Users/Pc/Downloads/data.csv.zip",encoding= "latin1")
print(df)

       InvoiceNo StockCode                          Description  Quantity  \
0         536365    85123A   WHITE HANGING HEART T-LIGHT HOLDER         6
1         536365     71053                  WHITE METAL LANTERN         6
2         536365    84406B       CREAM CUPID HEARTS COAT HANGER         8
3         536365    84029G  KNITTED UNION FLAG HOT WATER BOTTLE         6
4         536365    84029E       RED WOOLLY HOTTIE WHITE HEART.         6
...          ...       ...                                  ...       ...
541904    581587     22613          PACK OF 20 SPACEBOY NAPKINS        12
541905    581587     22899         CHILDREN'S APRON DOLLY GIRL          6
541906    581587     23254        CHILDRENS CUTLERY DOLLY GIRL          4
541907    581587     23255      CHILDRENS CUTLERY CIRCUS PARADE         4
541908    581587     22138        BAKING SET 9 PIECE RETROSPOT          3

            InvoiceDate  UnitPrice  CustomerID         Country
0        12/1/2010 8:26       2.55     17850.0  United Kingdom
1        12/1/2010 8:26       3.39     17850.0  United Kingdom
2        12/1/2010 8:26       2.75     17850.0  United Kingdom
3        12/1/2010 8:26       3.39     17850.0  United Kingdom
4        12/1/2010 8:26       3.39     17850.0  United Kingdom
...                 ...        ...         ...             ...
541904  12/9/2011 12:50       0.85     12680.0          France
541905  12/9/2011 12:50       2.10     12680.0          France
541906  12/9/2011 12:50       4.15     12680.0          France
541907  12/9/2011 12:50       4.15     12680.0          France
541908  12/9/2011 12:50       4.95     12680.0          France

[541909 rows x 8 columns]

In [5]:
df.head(20)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/1/2010 8:26,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12/1/2010 8:26,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
5,536365,22752,SET 7 BABUSHKA NESTING BOXES,2,12/1/2010 8:26,7.65,17850.0,United Kingdom
6,536365,21730,GLASS STAR FROSTED T-LIGHT HOLDER,6,12/1/2010 8:26,4.25,17850.0,United Kingdom
7,536366,22633,HAND WARMER UNION JACK,6,12/1/2010 8:28,1.85,17850.0,United Kingdom
8,536366,22632,HAND WARMER RED POLKA DOT,6,12/1/2010 8:28,1.85,17850.0,United Kingdom
9,536367,84879,ASSORTED COLOUR BIRD ORNAMENT,32,12/1/2010 8:34,1.69,13047.0,United Kingdom
10,536367,22745,POPPY'S PLAYHOUSE BEDROOM,6,12/1/2010 8:34,2.10,13047.0,United Kingdom
11,536367,22748,POPPY'S PLAYHOUSE KITCHEN,6,12/1/2010 8:34,2.10,13047.0,United Kingdom
12,536367,22749,FELTCRAFT PRINCESS CHARLOTTE DOLL,8,12/1/2010 8:34,3.75,13047.0,United Kingdom
13,536367,22310,IVORY KNITTED MUG COSY,6,12/1/2010 8:34,1.65,13047.0,United Kingdom
14,536367,84969,BOX OF 6 ASSORTED COLOUR TEASPOONS,6,12/1/2010 8:34,4.25,13047.0,United Kingdom
15,536367,22623,BOX OF VINTAGE JIGSAW BLOCKS,3,12/1/2010 8:34,4.95,13047.0,United Kingdom
16,536367,22622,BOX OF VINTAGE ALPHABET BLOCKS,2,12/1/2010 8:34,9.95,13047.0,United Kingdom
17,536367,21754,HOME BUILDING BLOCK WORD,3,12/1/2010 8:34,5.95,13047.0,United Kingdom
18,536367,21755,LOVE BUILDING BLOCK WORD,3,12/1/2010 8:34,5.95,13047.0,United Kingdom
19,536367,21777,RECIPE BOX WITH METAL HEART,4,12/1/2010 8:34,7.95,13047.0,United Kingdom

In [6]:
print("Shape(row,cols:)",df.shape)

Shape(row,cols:) (541909, 8)

In [7]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 541909 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    541909 non-null  object
 1   StockCode    541909 non-null  object
 2   Description  540455 non-null  object
 3   Quantity     541909 non-null  int64
 4   InvoiceDate  541909 non-null  object
 5   UnitPrice    541909 non-null  float64
 6   CustomerID   406829 non-null  float64
 7   Country      541909 non-null  object
dtypes: float64(2), int64(1), object(5)
memory usage: 33.1+ MB
None

In [8]:
print("\nColumns-wise missing values:\n",df.isnull().sum())

Columns-wise missing values:
 InvoiceNo           0
StockCode           0
Description      1454
Quantity            0
InvoiceDate         0
UnitPrice           0
CustomerID     135080
Country             0
dtype: int64

In [9]:
print("\nBasic statistics:\n",df.describe())

Basic statistics:
             Quantity      UnitPrice     CustomerID
count  541909.000000  541909.000000  406829.000000
mean        9.552250       4.611114   15287.690570
std       218.081158      96.759853    1713.600303
min    -80995.000000  -11062.060000   12346.000000
25%         1.000000       1.250000   13953.000000
50%         3.000000       2.080000   15152.000000
75%        10.000000       4.130000   16791.000000
max     80995.000000   38970.000000   18287.000000

In [10]:
df = df.dropna(subset=["Description"])

In [11]:
df

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/1/2010 8:26,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12/1/2010 8:26,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
...,...,...,...,...,...,...,...,...
541904,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,12/9/2011 12:50,0.85,12680.0,France
541905,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,12/9/2011 12:50,2.10,12680.0,France
541906,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,12/9/2011 12:50,4.15,12680.0,France
541907,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,12/9/2011 12:50,4.15,12680.0,France
541908,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,12/9/2011 12:50,4.95,12680.0,France

In [12]:
print("\nColumns-wise missing values:\n",df.isnull().sum())

Columns-wise missing values:
 InvoiceNo           0
StockCode           0
Description         0
Quantity            0
InvoiceDate         0
UnitPrice           0
CustomerID     133626
Country             0
dtype: int64

In [13]:
df_with_customer = df.dropna(subset=["CustomerID"]).copy()
df_with_customer["CustomerID"]=df_with_customer["CustomerID"].astype(int)

print(df_with_customer)

       InvoiceNo StockCode                          Description  Quantity  \
0         536365    85123A   WHITE HANGING HEART T-LIGHT HOLDER         6
1         536365     71053                  WHITE METAL LANTERN         6
2         536365    84406B       CREAM CUPID HEARTS COAT HANGER         8
3         536365    84029G  KNITTED UNION FLAG HOT WATER BOTTLE         6
4         536365    84029E       RED WOOLLY HOTTIE WHITE HEART.         6
...          ...       ...                                  ...       ...
541904    581587     22613          PACK OF 20 SPACEBOY NAPKINS        12
541905    581587     22899         CHILDREN'S APRON DOLLY GIRL          6
541906    581587     23254        CHILDRENS CUTLERY DOLLY GIRL          4
541907    581587     23255      CHILDRENS CUTLERY CIRCUS PARADE         4
541908    581587     22138        BAKING SET 9 PIECE RETROSPOT          3

            InvoiceDate  UnitPrice  CustomerID         Country
0        12/1/2010 8:26       2.55       17850  United Kingdom
1        12/1/2010 8:26       3.39       17850  United Kingdom
2        12/1/2010 8:26       2.75       17850  United Kingdom
3        12/1/2010 8:26       3.39       17850  United Kingdom
4        12/1/2010 8:26       3.39       17850  United Kingdom
...                 ...        ...         ...             ...
541904  12/9/2011 12:50       0.85       12680          France
541905  12/9/2011 12:50       2.10       12680          France
541906  12/9/2011 12:50       4.15       12680          France
541907  12/9/2011 12:50       4.15       12680          France
541908  12/9/2011 12:50       4.95       12680          France

[406829 rows x 8 columns]

In [14]:
df_with_customer["CustomerID"]

0         17850
1         17850
2         17850
3         17850
4         17850
          ...
541904    12680
541905    12680
541906    12680
541907    12680
541908    12680
Name: CustomerID, Length: 406829, dtype: int64

In [15]:
df.duplicated().count()

np.int64(540455)

In [16]:
print("\nBasic statistics:\n",df.describe())

Basic statistics:
             Quantity      UnitPrice     CustomerID
count  540455.000000  540455.000000  406829.000000
mean        9.603129       4.623519   15287.690570
std       218.007598      96.889628    1713.600303
min    -80995.000000  -11062.060000   12346.000000
25%         1.000000       1.250000   13953.000000
50%         3.000000       2.080000   15152.000000
75%        10.000000       4.130000   16791.000000
max     80995.000000   38970.000000   18287.000000

In [17]:
#Check IScancelled Payment and Invoice number and check data type 'confirm false','cancelled true'
df["IsCancelled"]=df["InvoiceNo"].astype(str).str.startswith("C").sum()

In [18]:
df["IsCancelled"]

0         9288
1         9288
2         9288
3         9288
4         9288
          ...
541904    9288
541905    9288
541906    9288
541907    9288
541908    9288
Name: IsCancelled, Length: 540455, dtype: int64

In [19]:
#Create a new Dataframe only keeping Valid Transaction 
df_clean = df[
           (~df["IsCancelled"]) &
           (df["Quantity"] > 0) &
           (df["UnitPrice"] > 0)].copy()

In [20]:
df_clean

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,IsCancelled
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/1/2010 8:26,2.55,17850.0,United Kingdom,9288
1,536365,71053,WHITE METAL LANTERN,6,12/1/2010 8:26,3.39,17850.0,United Kingdom,9288
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12/1/2010 8:26,2.75,17850.0,United Kingdom,9288
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12/1/2010 8:26,3.39,17850.0,United Kingdom,9288
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,12/1/2010 8:26,3.39,17850.0,United Kingdom,9288
...,...,...,...,...,...,...,...,...,...
541904,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,12/9/2011 12:50,0.85,12680.0,France,9288
541905,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,12/9/2011 12:50,2.10,12680.0,France,9288
541906,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,12/9/2011 12:50,4.15,12680.0,France,9288
541907,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,12/9/2011 12:50,4.15,12680.0,France,9288
541908,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,12/9/2011 12:50,4.95,12680.0,France,9288

In [21]:
#This allows us to perform data and time analysis (e.g year, month ,day, hour)
df_clean["InvoiceDate"] = pd.to_datetime(df_clean["InvoiceDate"],format = "%m/%d/%Y %H:%M")

In [22]:
df_clean["InvoiceDate"]

0        2010-12-01 08:26:00
1        2010-12-01 08:26:00
2        2010-12-01 08:26:00
3        2010-12-01 08:26:00
4        2010-12-01 08:26:00
                 ...
541904   2011-12-09 12:50:00
541905   2011-12-09 12:50:00
541906   2011-12-09 12:50:00
541907   2011-12-09 12:50:00
541908   2011-12-09 12:50:00
Name: InvoiceDate, Length: 530104, dtype: datetime64[ns]

In [23]:
# Create a new column 'TotalPrice' to calculate the total amount for each transaction
df_clean["TotalPrice"]= np.multiply(df_clean["Quantity"],df_clean["UnitPrice"])

In [24]:
df_clean["TotalPrice"]

0         15.30
1         20.34
2         22.00
3         20.34
4         20.34
          ...
541904    10.20
541905    12.60
541906    16.60
541907    16.60
541908    14.85
Name: TotalPrice, Length: 530104, dtype: float64

print("STEP 3: Data Cleaned")
print("Original rows:",df.shape[0],"|Clean rows:" df_clean.shape[0])
print("Cancelled orders removed:",df[IsCancelled].sum())
print(df_clean[["InvoiceNo", "Quantity","UnitPrice","TotalPrice", "InvoiceDate"]].head())
print("\n")

In [34]:
# Data-Based features(for time analysis)

In [25]:
#Extract the year from the 'InvoiceDate' column and store it in a new column 'year'

df_clean["Year"] = df_clean["InvoiceDate"].dt.year

#Extract the month (1-12) from the 'InvoiceDate' column

df_clean["Month"] = df_clean["InvoiceDate"].dt.month

#Extract the day of the month(1-31) from the 'InvoiceDate' column
df_clean["Day"] = df_clean["InvoiceDate"].dt.day

#Extract the day of the hour (0-23) from the 'InvoiceDate' column
df_clean["Hour"] = df_clean["InvoiceDate"].dt.hour

#Extract the name of the day of the week
df_clean["DayofWeek"] = df_clean["InvoiceDate"].dt.day_name()

In [26]:
df_clean["DayofWeek"]

0         Wednesday
1         Wednesday
2         Wednesday
3         Wednesday
4         Wednesday
            ...
541904       Friday
541905       Friday
541906       Friday
541907       Friday
541908       Friday
Name: DayofWeek, Length: 530104, dtype: object

In [27]:
df_clean["Hour"]

0          8
1          8
2          8
3          8
4          8
          ..
541904    12
541905    12
541906    12
541907    12
541908    12
Name: Hour, Length: 530104, dtype: int32

In [28]:
print("Step 4: Data features added")
print(df_clean[["InvoiceDate","Year", "Month", "DayofWeek", "Hour"]].head(10))
print("\n")

Step 4: Data features added
          InvoiceDate  Year  Month  DayofWeek  Hour
0 2010-12-01 08:26:00  2010     12  Wednesday     8
1 2010-12-01 08:26:00  2010     12  Wednesday     8
2 2010-12-01 08:26:00  2010     12  Wednesday     8
3 2010-12-01 08:26:00  2010     12  Wednesday     8
4 2010-12-01 08:26:00  2010     12  Wednesday     8
5 2010-12-01 08:26:00  2010     12  Wednesday     8
6 2010-12-01 08:26:00  2010     12  Wednesday     8
7 2010-12-01 08:28:00  2010     12  Wednesday     8
8 2010-12-01 08:28:00  2010     12  Wednesday     8
9 2010-12-01 08:34:00  2010     12  Wednesday     8

In [29]:
# formula:total revenue = sum of totalprice values
total_revenue = np.sum(df_clean["TotalPrice"])

In [33]:
# nunique() counts unique Invoiceno values
# If an invoice contains multiple products , it is still counted as One Order
total_orders = df_clean["InvoiceNo"].nunique()

#Calculate the total number of unique customers
#nunique() counts distinct customerId values
#If a customer places multiple orders they are counted only once 
total_customers =  df_clean["CustomerID"].nunique()

# Calculate the Average Order Value(AOV)
#1. Group all rows by InvoiceNo (each invoice may contain multiple products).
#2. Sum the totaprice of all products within each invoice 
#3. Calculate the average of all invoice totals 
avg_order_value = df_clean.groupby("InvoiceNo")["TotalPrice"].sum().mean()

In [34]:
# Display the result 
print("Step5: Key Metrics")
print(f"Total Revenue: {total_revenue:,.2f}")
print(f"Total Unique Orders:{total_orders}")
print(f"Total Unique Customers:{total_customers}")
print(f"Average Order Value: {avg_order_value:,.2f}")
print("\n")

Step5: Key Metrics
Total Revenue: 10,666,684.54
Total Unique Orders:19960
Total Unique Customers:4338
Average Order Value: 534.40

In [36]:
#Find the top 10 products that generated the highest total revenue

top_products_revenue = (
    df_clean.groupby("Description")["TotalPrice"]
    .sum()
    .sort_values(ascending=False)
    .head(10)
)
#Find the top 10 products sold in the highest quantities 
top_products_qty= (
    df_clean.groupby("Description")["Quantity"]
    .sum()
    .sort_values(ascending=False)
    .head(10)

)

In [37]:
#Display the results 
print("STEP 6: Top 10 Products by Revenue")
print(top_products_revenue)
print("STEP 7: Top 10 Products by Quantity")
print(top_products_qty)
print("\n")

STEP 6: Top 10 Products by Revenue
Description
DOTCOM POSTAGE                        206248.77
REGENCY CAKESTAND 3 TIER              174484.74
PAPER CRAFT , LITTLE BIRDIE           168469.60
WHITE HANGING HEART T-LIGHT HOLDER    106292.77
PARTY BUNTING                          99504.33
JUMBO BAG RED RETROSPOT                94340.05
MEDIUM CERAMIC TOP STORAGE JAR         81700.92
Manual                                 78112.82
POSTAGE                                78101.88
RABBIT NIGHT LIGHT                     66964.99
Name: TotalPrice, dtype: float64
STEP 7: Top 10 Products by Quantity
Description
PAPER CRAFT , LITTLE BIRDIE           80995
MEDIUM CERAMIC TOP STORAGE JAR        78033
WORLD WAR 2 GLIDERS ASSTD DESIGNS     55047
JUMBO BAG RED RETROSPOT               48474
WHITE HANGING HEART T-LIGHT HOLDER    37891
POPCORN HOLDER                        36761
ASSORTED COLOUR BIRD ORNAMENT         36461
PACK OF 72 RETROSPOT CAKE CASES       36419
RABBIT NIGHT LIGHT                    30788
MINI PAINT SET VINTAGE                26633
Name: Quantity, dtype: int64

In [38]:
#Step 7 : Country -wise Analysis

In [39]:
# Calculate the total revenue generated by each country and sort it from highest to lowest 
country_revenue = (
    df_clean.groupby("Country")["TotalPrice"]
    .sum()
    .astype(int)
    .sort_values(ascending=False)
)

In [40]:
# Display the result

print("STEP 7: Revenue by Country(Top 10)")
print(country_revenue.head(10))
print("\n")

STEP 7: Revenue by Country(Top 10)
Country
United Kingdom    9025222
Netherlands        285446
EIRE               283453
Germany            228867
France             209715
Australia          138521
Spain               61577
Switzerland         57089
Belgium             41196
Sweden              38378
Name: TotalPrice, dtype: int64

In [42]:
#STEP 8: Monthly Sales Trend

In [43]:
#Create a nwe column containing only the year and Month from the InvoiceDate

df_clean["YearMonth"] = df_clean["InvoiceDate"].dt.to_period("M")

#Create the total sales (revenue) for each Year-Month
monthly_sales = df_clean.groupby("YearMonth")["TotalPrice"].sum()

In [44]:
# Display the result 
print("STEP 8: Monthly Revenue Trend")
print(monthly_sales)
print("\n")

STEP 8: Monthly Revenue Trend
YearMonth
2010-12     823746.140
2011-01     691364.560
2011-02     523631.890
2011-03     717639.360
2011-04     537808.621
2011-05     770536.020
2011-06     761739.900
2011-07     719221.191
2011-08     759138.380
2011-09    1058590.172
2011-10    1154979.300
2011-11    1509496.330
2011-12     638792.680
Freq: M, Name: TotalPrice, dtype: float64

In [45]:
#STEP9 :DAYWISE SALES TREND

# Create a new column containing only the year and day from the invoicedate 
df_clean["YearDay"] = df_clean["InvoiceDate"].dt.to_period("D")

daywise_sales = df_clean.groupby("YearDay")["TotalPrice"].sum()

In [47]:
print("Step 9: Daywise Revenue Trend")
print(daywise_sales)
print("\n")

Step 9: Daywise Revenue Trend
YearDay
2010-12-01     58960.79
2010-12-02     47748.38
2010-12-03     46943.71
2010-12-05     31774.95
2010-12-06     54830.46
                ...
2011-12-05     88741.96
2011-12-06     56713.21
2011-12-07     75439.16
2011-12-08     82495.00
2011-12-09    200920.60
Freq: D, Name: TotalPrice, Length: 305, dtype: float64

# CUSTOMER ANALYSIS

In [51]:
# Create a customer summary by calculating, spending orders, average order value, and last purchase date, then sort 
# customers by highest total spending

customer_summary = df_clean.groupby("CustomerID").agg(
    TotalSpent=("TotalPrice","sum"),
    NumOrders=("InvoiceNo","nunique"),
    AvgOrderValue=("TotalPrice","mean"),
    LastPurchase=("InvoiceDate","max")
).sort_values("TotalSpent",ascending=False)

In [53]:
#Show the result 
print("Step 9: Top 10 customers by Total Spend")
print(customer_summary.head(5))
print("\n")

Step 9: Top 10 customers by Total Spend
            TotalSpent  NumOrders  AvgOrderValue        LastPurchase
CustomerID
14646.0      280206.02         73     134.973998 2011-12-08 12:12:00
18102.0      259657.30         60     602.453132 2011-12-09 11:50:00
17450.0      194550.79         46     577.302047 2011-12-01 13:29:00
16446.0      168472.50          2   56157.500000 2011-12-09 09:15:00
14911.0      143825.06        201      25.343623 2011-12-08 15:54:00

# Numpy-based statistical analysis on order values

In [54]:
# Calculate the total value of each order (invoice) and store the results as a Numpy array
order_values = df_clean.groupby("InvoiceNo")["TotalPrice"].sum().values

In [55]:
order_values

array([  139.12,    22.2 ,   278.73, ...,   339.2 ,   249.45, 11062.06])

In [56]:
# Step 10: Calculate and display basic statistics fororder values 

print("STEP 10 : Order Value Statistics(Numpy)")

# Display the average order value 
print("Mean:",np.mean(order_values))

#Display the middle order value 
print("Median:",np.median(order_values))
 #Display the spread of order values 
print("Standard Deviation:",np.std(order_values))

#Display the smallest order value 
print("Minimum:",np.min(order_values))

#Display the largest order value
print("Maximum",np.max(order_values))

# Display the value below which 25% of orders fall
print("25th Percentile:",np.percentile(order_values, 25))

# Display the value below which 75% of orders fall
print("75th Percentile:",np.percentile(order_values, 75))

STEP 10 : Order Value Statistics(Numpy)
Mean: 534.403033266533
Median: 303.83500000000004
Standard Deviation: 1780.4430456461234
Minimum: 0.38
Maximum 168469.6
25th Percentile: 152.51
75th Percentile: 495.615

In [ ]:
#STEP 11: Save cleaned data & summary outputs

In [57]:
#Save the cleaned dataset to a CSV file without including the row index
df_clean.to_csv("Cleaned_ecommerce_data.csv",index=False)

#Save the customer summary report to a csv file 
customer_summary.to_csv("customer_summary.csv")

#Save the country-wise revenue report to csv file 
country_revenue.to_csv("country_revenue.csv")

In [58]:
print("Step 11: File saved -> cleaned_ecommerce_data.csv, customer_summary.csv, country_revenue.csv")

Step 11: File saved -> cleaned_ecommerce_data.csv, customer_summary.csv, country_revenue.csv